version: "3.7"
volumes:
  volume-db:
  volume_static:
  volume_media:
  volume_redis:
  volume_rq:
services:
  web:
    build:
      context: ./server
    container_name: homework-checker-web
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: homework-checker-db
    restart: always
    volumes:
      - volume_static:/home/app/web/staticfiles:rw
      - volume_media:/home/app/web/mediafiles:rw
  db:
    container_name: homework-checker-db
    image: postgres:12-alpine
    expose:
      - 5432
    restart: always
    volumes:
      - volume-db:/var/lib/postgresql/data
  redis:
    container_name: homework-checker-redis
    image: redis:6-alpine
    expose:
      - 6379
    restart: always
    volumes:
      - volume_redis:/data
  rq:
    container_name: homework-checker-rq
    command: python manage.py rqworker default
    build:
      context: ./server
    environment:
      POSTGRES_HOST: homework-checker-db
    restart: always
    volumes:
      - volume_rq:/rqdata
      - volume_media:/home/app/web/mediafiles
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - db
  client:
    container_name: homework-checker-client
    build:
      context: ./client
    restart: always
    volumes:
      - ./client/node_modules:/app/node_modules
    depends_on:
      - web
