version: '3.7'
volumes:
    static_volume:
    media_volume:
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        expose:
            - 8000
        env_file:
            - ./server/.env.prod
    app-db:
        restart: always
        env_file:
            - ./server/.env.prod
    app-nginx:
        build: ./nginx
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        ports:
            - 1337:80
        depends_on:
            - app-web
