version: '3.7'
volumes:
    app-db:
    static_volume:
    media_volume:
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        env_file:
            - ./server/.env.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
    app-db:
        restart: always
        env_file:
            - ./server/.env.prod
    app-client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        volumes:
          - static_volume:/var/www/staticfiles
          - media_volume:/var/www/mediafiles
        ports:
            - 1337:8080
