version: '3.7'
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        command: python manage.py runserver 0.0.0.0:8000
        env_file:
            - ./server/.env.dev
    app-db:
        env_file:
            - ./server/.env.dev

    app-client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes:
          - ./client:/app
        ports:
            - 3001:3000
        environment:
          - CHOKIDAR_USEPOLLING=true
        command: npm start
