version: '3.7'
volumes:
    app-db:
    static_volume:
    media_volume:
    redisdata:
    rqdata:
services:
    app-web:
        build:
            context: ./server
        container_name: app-web
        depends_on:
            - app-db
            - app-redis
        environment:
            POSTGRES_HOST: app-db
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
            - ./server/:/home/app/web/
    app-db:
        container_name: app-db
        image: postgres:12-alpine
        expose:
            - 5432
        volumes:
         - app-db:/var/lib/postgresql/data
    app-redis:
        container_name: app-redis
        image: redis:6-alpine
        restart: always
        ports:
            - 6379:6379
        volumes:
            - redisdata:/data
    app-rq:
        build:
            context: ./server
            dockerfile: Dockerfile.rq
        container_name: app-rq
        environment:
            POSTGRES_HOST: app-db
        restart: always
        volumes:
            - rqdata:/rqdata
            - /var/run/docker.sock:/var/run/docker.sock
        depends_on:
            - app-redis
            - app-db
    app-client:
        container_name: app-client
        build:
            context: ./client
        stdin_open: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
          - app-web


