version: '3.7'
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        ports:
            - 8003:8000
        env_file:
            - ./server/.env.dev
    app-db:
        env_file:
            - ./server/.env.dev
