services:
    app-server:
        build:
            dockerfile: Dockerfile.prod
        env_file:
            - ./server/.env.prod
    app-db:
        restart: always
        env_file:
            - ./server/.env.prod
