version: "3.7"
volumes:
  volume-db:
  volume-static:
  volume-media:
  volume-redis:
  volume-rq:
services:
  web:
    build:
      context: ./server
    container_name: homework-checker-web
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
    restart: unless-stopped
    volumes:
      - volume-static:/home/app/web/staticfiles:rw
      - volume-media:/home/app/web/mediafiles:rw
  db:
    container_name: homework-checker-db
    image: postgres:12-alpine
    expose:
      - 5432
    restart: unless-stopped
    volumes:
      - volume-db:/var/lib/postgresql/data
  redis:
    container_name: homework-checker-redis
    image: redis:6-alpine
    expose:
      - 6379
    restart: unless-stopped
    volumes:
      - volume-redis:/data
  rq:
    container_name: homework-checker-rq
    command: python manage.py rqworker default
    build:
      context: ./server
    environment:
      POSTGRES_HOST: db
    restart: unless-stopped
    volumes:
      - volume-rq:/rqdata
      - volume-media:/home/app/web/mediafiles
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
      - db
  client:
    container_name: homework-checker-client
    build:
      context: ./client
    restart: unless-stopped
    depends_on:
      - web
