version: '3.7'
volumes:
    app-db:
services:
    app-web:
        build:
            context: ./server
        container_name: app-web
        command: python manage.py runserver 0.0.0.0:8000
        depends_on:
            - app-db
            - app-redis
        environment:
            POSTGRES_HOST: app-db
        volumes:
            - ./server:/usr/src/app
    app-db:
        container_name: app-db
        image: postgres:12-alpine
        expose:
            - 5432
        volumes:
         - app-db:/var/lib/postgresql/data
    app-redis:
        container_name: app-redis
        image: redis:6-alpine
    app-client:
        container_name: app-client
        build:
            context: ./client
        command: npm start
        depends_on:
            - app-web
        ports:
            - 3001:3000
        stdin_open: true
        volumes:
          - ./client:/usr/src/app
        environment:
          - CHOKIDAR_USEPOLLING=true
          - REACT_APP_BASE_URL=http://localhost:8003


