version: '3.7'
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        env_file:
            - ./server/.env.prod
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    app-db:
        restart: always
        env_file:
            - ./server/.env.prod

    app-rq:
        command: python manage.py rqworker default
        env_file:
            - ./server/.env.prod
        build:
            context: ./server
            dockerfile: Dockerfile.rq
    app-client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        volumes:
          - static_volume:/var/www/staticfiles
          - media_volume:/var/www/mediafiles
        ports:
            - 80:8080
