version: '3.7'
volumes:
    app-db:
services:
    app-server:
        container_name: app-server
        build:
            context: ./server
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8003:8000
        depends_on:
            - app-db
            - app-redis
        environment:
            POSTGRES_HOST: app-db
            POSTGRES_PORT: 5432
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            REDIS_URL: redis://app-redis:6379/0
        volumes:
            - ./server:/usr/src/app
    app-db:
        image: postgres:12-alpine
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        expose:
            - 5432
        volumes:
         - app-db:/var/lib/postgresql/data
    app-redis:
        container_name: app-redis
        image: redis:6-alpine
    app-client:
        container_name: app-client
        build:
            context: ./client
        command: npm start
        depends_on:
            - app-server
        ports:
            - 3001:3000
        stdin_open: true
        volumes:
          - ./client:/usr/src/app
        environment:
          - CHOKIDAR_USEPOLLING=true
          - REACT_APP_BASE_URL=http://localhost:8003


