version: '3.7'
volumes:
    app-db:
services:
    app-web:
        build:
            context: ./server
        container_name: app-web
        depends_on:
            - app-db
            - app-redis
        ports:
            - 8003:8000
        environment:
            POSTGRES_HOST: app-db
    app-db:
        container_name: app-db
        image: postgres:12-alpine
        expose:
            - 5432
        volumes:
         - app-db:/var/lib/postgresql/data
    app-redis:
        container_name: app-redis
        image: redis:6-alpine
    app-client:
        container_name: app-client
        build:
            context: ./client
        stdin_open: true
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
          - app-web


