version: '3.7'
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.prod
        env_file:
            - .env/production.env
        command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    app-db:
        restart: always
        env_file:
            - .env/production.env

    app-rq:
        command: python manage.py rqworker default
        env_file:
            - .env/production.env
        build:
            context: ./server
            dockerfile: Dockerfile.dev
    app-client:
        build:
            context: ./client
            dockerfile: Dockerfile.prod
        volumes:
          - static_volume:/var/www/staticfiles
          - media_volume:/var/www/mediafiles
          - /etc/letsencrypt:/etc/letsencrypt
          - /var/lib/letsencrypt:/var/lib/letsencrypt
        ports:
            - 80:80
            - 443:443
