version: '3.7'
services:
    app-web:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        env_file:
            - ./server/.env.dev
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - 8000:8000
    app-db:
        restart: always
        env_file:
            - ./server/.env.dev
    app-rq:
        command: python manage.py rqworker default
        env_file:
            - ./server/.env.dev
    app-client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        ports:
            - 3001:3000
        environment:
          - CHOKIDAR_USEPOLLING=true
        command: npm start
