version: '3.7'

services:
    app:
        build: ./src
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./src/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./src/.env.dev
        depends_on:
            - app_db
    app_db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_DB=teaching_dev
            - POSTGRES_USER=teaching
            - POSTGRES_PASSWORD=teaching

volumes:
    postgres_data:
